/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package joke.api;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

import joke.api.entities.Joke;
import joke.api.repositories.JokeRepository;

@SpringBootApplication
public class App implements CommandLineRunner {
    private static final Logger LOG = LoggerFactory.getLogger(App.class);

    @Autowired
    private JokeRepository jokeRepository;

    public static void main(String[] args) {
        LOG.info("STARTING THE APPLICATION");
        SpringApplication.run(App.class, args);
        LOG.info("APPLICATION FINISHED");
    }

    @Override
    public void run(String... args) throws Exception {
        LOG.info("Running the application");

        LOG.info("Executing pre-launch hibernate checks");
        Joke firstJoke = jokeRepository.findById(1L).orElse(null);
        LOG.info("First joke: {}", firstJoke);

        LOG.info("Number of jokes in the database: {}", jokeRepository.count());
    }
}
